# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Merge Request

on:
  pull_request:
#
#TEST
#
jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: none
      issues: write
      discussions: write
      packages: write
      pull-requests: write
      repository-projects: none
      security-events: none
      statuses: write
    # Concurrency enables the option to cancel obsolet Jobs
    concurrency:
      group: pr_build_${{ github.head_ref }}
      cancel-in-progress: true

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn -B verify --file org.eclipse.scout.hellojava/pom.xml
    # XML Parser to display Test Results
    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: always()
      with:
        files: "*/target/surefire-reports/**/*.xml"

#     - name: Publish to GitHub Packages Apache Maven
#       run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
#       env:
#         GITHUB_TOKEN: ${{ github.token }}
